### ISSUE TITLE
Decorator Pattern

### ISSUE THREAD

**Issue by emuyuu** [emuyuu/design_pattern#4]
# 観点

- いつこの機能を使うか？
- 類似機能との違いは何か？

# カリキュラム

- [x] 一般的によく使われているdecorator解説 @emuyuu 
- [x] TODOの解析 @zynaxsoft
- [x] 疑問は随時ディベート 
- [x] 残りのdecorator手法解説

**Comment by EngineerLabShimazu** [comment]
次回からココ参考にしましょ〜
https://github.com/faif/python-patterns
